name: 'PHP Setup'
description: 'Setup PHP with required extensions'

inputs:
  php-version:
    description: 'PHP version to install'
    required: true
    default: '8.4'
  extensions:
    description: 'Comma-separated list of PHP extensions to install'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
