FROM php:8.4-cli

# Install dependencies and required libraries for PHP extensions
RUN apt-get update && apt-get install -y \
    libcurl4-openssl-dev \
    libzip-dev \
    libmagickwand-dev \
    libpng-dev \
    libjpeg-dev \
    libfreetype6-dev \
    libxml2-dev \
    libssl-dev \
    libonig-dev \
    libmcrypt-dev \
    libgmp-dev \
    libtidy-dev \
    libxslt1-dev \
    libreadline-dev \
    libbz2-dev \
    && docker-php-ext-configure gd --with-freetype --with-jpeg \
    && docker-php-ext-install \
    bcmath \
    bz2 \
    calendar \
    exif \
    gd \
    gettext \
    imagick \
    intl \
    mbstring \
    mysqli \
    opcache \
    pcntl \
    pdo \
    pdo_mysql \
    pdo_pgsql \
    soap \
    sockets \
    sysvmsg \
    sysvsem \
    sysvshm \
    xml \
    xsl \
    zip \
    && pecl install redis \
    && docker-php-ext-enable redis \
    && pecl install imagick \
    && docker-php-ext-enable imagick \
    && pecl install gmp \
    && docker-php-ext-enable gmp \
    && pecl install tidy \
    && docker-php-ext-enable tidy

# Optional: Install additional PHP extensions based on the input
ARG PHP_EXTENSIONS
RUN if [ -n "$PHP_EXTENSIONS" ]; then \
        IFS=',' read -r -a extensions <<< "$PHP_EXTENSIONS"; \
        for ext in "${extensions[@]}"; do \
            docker-php-ext-install "$ext"; \
        done; \
    fi

# Set the entry point
ENTRYPOINT ["./entrypoint.sh"]
